name: VM Deployment Recipe Pipeline

on:
 workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run deployments against'
        type: environment
        required: true
        options:
          - qa
          - prod
          - dev
      terraform_action:
        description: 'The action terraform should apply'
        type: choice
        options:
          - plan
          - apply
          - destroy
        required: true
        default: 'apply'
      run_bash:
         description: 'To run the bash'
         type: choice
         options:
          - Yes
          - No
         required: true
 push:
    branches:
      - main
    paths:
      - '.github/workflows/Reusable-*'
 pull_request:
    branches:
      - feature/**
    paths:
      - '.github/workflows/Reusable-*'

permissions:
      id-token: write
      contents: read
      pull-requests: "write"

jobs:
 build:
    uses: ./.github/workflows/Reusable-VM-Deployment-Build.yaml
    with:
      build_env: ${{ github.event.inputs.environment }}
      tf_action: ${{ github.event.inputs.terraform_action }}
      run_bash:  ${{ github.event.inputs.run_bash }}
    secrets: inherit
